source "https://rubygems.org"

gem "github-pages"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-assets"
gem "jekyll-archives"
gem "mini_magick"
gem "autoprefixer-rails"
gem "sprockets-es6"
gem "bootstrap-sass"
gem "font-awesome-sass"
gem "octopress", '~> 3.0'